### ISSUE TITLE
Clssifier

### ISSUE THREAD

**Issue by lys15163238308** [isaksamsten/castor#1]
Hello, wildboar.linear_models dont have CastorClassifier.

**Comment by isaksamsten** [comment]
Hi! Small misspelling. It should be linear_model

**Comment by lys15163238308** [comment]
Hi~ thanks for your reply. I would like to use your algorithm in my own database, and I wonder if you can use any database as an example to implement a binary classification. Looking forward to your reply.

**Comment by isaksamsten** [comment]
Hi!

Yes! You can use it for your own data. 

The fit-method accepts two numpy arrays X with n rows (time series) and m columns (time step/timepoint) and a 1d array with n values where each value is a label for the i:th time series. 

Isak

**Comment by lys15163238308** [comment]
Thank you very much for your reply~
